### ISSUE TITLE
xml to prc

### ISSUE THREAD

**Issue by schiggysmallz** [BenHall-7/paracobNET#1]
when i try to convert a xml back to prc i get this error

`C:\Users\Chris\Desktop\Smash Ultimate Mods\Tools\CrossArc\root\ui\param\database>dotnet C:\Users\Chris\Desktop\paracobNET-master\ParamXML\bin\Release\netcoreapp2.1\ParamXML.dll "C:\Users\Chris\Desktop\Smash Ultimate Mods\Tools\CrossArc\root\ui\param\
database\ui_chara_db.xml"
Initializing...
File contains an invalid header
   at paracobNET.ParamFile..ctor(String filepath) in C:\Users\Chris\Desktop\paracobNET-master\paracobNET\ParamFile.cs:line 56
   at ParamXML.Program.Main(String[] args) in C:\Users\Chris\Desktop\paracobNET-master\ParamXML\Program.cs:line 58
ParamXML: Convert Ultimate param (.prc) files to XML format or back.
required: [input]
optional: -h ; -help ; -o [output] ; -l [label file]
`

**Comment by BenHall-7** [comment]
Added xml to prc conversion now
